#!/bin/sh
. /etc/functions.sh
WAN=ppp0

echo "   Enabling DNAT port forward for Terminal Server"
iptables -t nat -A prerouting_wan -p tcp --dport 3389 -j DNAT --to 192.168.254.25
iptables        -A forwarding_wan -p tcp --dport 3389 -d 192.168.254.25 -j ACCEPT

echo "   Done!"
